cloud_id        = "CLOUD_ID"
cluster_name    = "CLUSTER_NAME"
project_name    = "PROJECT_NAME"
bucket_name     = "BUCKET_NAME"
dbuser          = "USERNAME"
dbuser_password = "PASSWORD"
# ip_address      = "0.0.0.0/32"
